prestamosapp/urls.py
from django.urls import path,include
from prestamosapp import views
from django.contrib import admin
from django.conf import settings#ESTO ES PARA PODER VISUALIZAR LAS FOTOS
from django.conf.urls.static import static #ESTO ES PARA PODER VISUALIZAR LAS FOTOS

app_name='prestamosapp'
urlpatterns = [
    path('admin/', admin.site.urls), 
    path('clientes-saldo-cero/', views.clientes_con_saldo_cero, name='clientes_con_saldo_cero'),
    path('inicio/', views.inicio, name='inicio'),
    path('', views.cliente_list, name='cliente_list'),
    path('cliente_list/', views.cliente_list, name='cliente_list'),
    path('agregar_cliente/', views.add_cliente, name='agregar_cliente'),
    path('borrar_cliente<int:cliente_id>/', views.borrar_cliente, name='borrar_cliente'),
    path('informacion_cliente/<int:pk>/', views.cliente_full_info, name='informacion_cliente'),
    
    
    path('clientes/<int:cliente_id>/add_payment/', views.add_payment, name='add_payment'),
    path('cobro_del_dia/', views.cobro_del_dia, name='cobro_del_dia'),
    path('historia_cobro/', views.historial_cobro, name='historia_cobro'),
    

    
    path('clientes/<int:cliente_id>/edit/', views.edit_cliente, name='edit_cliente'),
    path('clientes/<int:cliente_id>/', views.historial_de_pagos, name='client_detail'),
    path('clientes/<int:cliente_id>/delete_payment/<int:payment_id>/', views.delete_payment, name='delete_payment'),
    
    path('agregar_gasto/', views.agregar_gasto, name='agregar_gasto'),
    path('lista_gastos_del_dia/', views.lista_gastos_del_dia, name='lista_gastos_del_dia'),
    path('gastos_semanales/', views.lista_gastos_de_la_semana, name='gastos_semanales'),
    path('gastos-del-mes/', views.lista_gastos_del_mes, name='gastos_del_mes'),
    path('todos-los-gastos/', views.lista_todos_los_gastos, name='todos_los_gastos'),
    
    path('agregar_base/', views.agregar_base, name='agregar_base'),
    path('historial_base/', views.historial_base, name='historial_base'),
    
    
    # BUSCADOR 
    path('search/', views.ClienteSearchView.as_view(), name='cliente-search'),
    
    path('liquidacion-del-dia/', views.liquidacion_del_Dia, name='liquidacion_del_dia'),
    path('liquidacion-total/', views.liquidacion_total, name='liquidacion_total'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #ESTO ES PARA PODER VISUALIZAR LAS FOTOS

project/urls.py
from django.contrib import admin
from django.urls import path, include
from prestamosapp import views
from django.conf import settings#ESTO ES PARA PODER VISUALIZAR LAS FOTOS
from django.conf.urls.static import static #ESTO ES PARA PODER VISUALIZAR LAS FOTOS
urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', views.inicio, name='inicio'),
    path('login/',views.login_user,name="login"),
    path('logout/',views.logout_user,name="logout"),
    path('', views.cliente_list, name='cliente_list'),
    path('prestamosapp/', include('prestamosapp.urls', namespace='prestamosapp')),
    
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #ESTO ES PARA PODER VISUALIZAR LAS FOTOS

prestamosapp/forms.py
from django import forms
from .models import Cliente,Payment
from .models import AgregarGasto,AgregarBase

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['order','nombre', 'apellidos', 'monto', 'direccion', 'descripcion_casa', 'foto_casa']
        #ESTO LO AGREGUE PARA EL METODO DE EDITAR CLIENTE Y QUE ESTOS CAMPOS NO SE PUEDAN EDITAR, QUE SE MUESTREN PERO SOLO COMO readonlyfields
        widgets = {
            #'monto': forms.TextInput(attrs={'readonly': 'readonly'}), ESTO LO BORRE PORQUE NO ME DEJABA AGREGAR MONTO A LA HORA DE INGRESAR EL CLIENTE, LO QUE NO QUIERO ES QUE FUNCIONE A LA HORA DE EDITARLO.
            'monto_mas_interes': forms.TextInput(attrs={'readonly': 'readonly'}),
            'saldo': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        monto = cleaned_data.get('monto')
        if monto:
            cleaned_data['monto_mas_interes'] = monto * 1.20  # Example calculation for 20% interest
            cleaned_data['couta_diaria'] = cleaned_data['monto_mas_interes'] / 20  # Example calculation for 20 days
        return cleaned_data
        
        
        
        
 #AL PRINCIPIO HABIAMOS HECHO EL METODO DE PAGOS SIN UN MODELO PERO ASI NO LO ESTABA GUARDANDO EN EL database ASI QUE NO PODIA MOSTRAR EL HISTORIAL DE PAGOS ,     
class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['payment_amount']
        
        
        


class AgregarGastoForm(forms.ModelForm):
    class Meta:
        model = AgregarGasto
        fields = ['descripcion_gasto', 'monto_gasto']
        
        

class AgregarBaseForm(forms.ModelForm):
    class Meta:
        model = AgregarBase
        fields = ['descripcion_base', 'monto_base']

prestamosapp/views.py
from django.shortcuts import render, redirect,get_object_or_404
from prestamosapp.models import Cliente,Payment
from prestamosapp.forms import PaymentForm
from prestamosapp.forms import ClienteForm
from django.utils import timezone
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def add_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST, request.FILES)
        if form.is_valid():
            cliente = form.save(commit=False)
            # Ensure monto_mas_interes and couta_diaria are calculated
            if not cliente.monto_mas_interes:
                cliente.monto_mas_interes = cliente.monto * 1.20  # Example calculation for 20% interest
            cliente.couta_diaria = cliente.monto_mas_interes / 20  # Example calculation for 20 days
            cliente.save()
            return redirect('prestamosapp:cliente_list')
    else:
        form = ClienteForm()
    
    context = {
        'form': form,
    }
    return render(request, 'add_cliente.html', context)

###################################################
#ESTO LO ESTOY HACIENDO PARA AL DARLE CLIC A TODA LA INFO DEL CLIENTE SE ME ABRA EN UNA NUEVA TEMPLATE 
def cliente_full_info(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    days_since_last_payment = cliente.days_since_last_payment()
    return render(request, 'detalles_cliente.html', {
        'cliente': cliente,
        'days_since_last_payment': days_since_last_payment
    })



def cliente_list(request):
    if request.method == 'POST':
        cliente_id = request.POST.get('cliente_id')
        payment_amount = request.POST.get('payment_amount')#ESTE ES EL FORM DE LOS PAGOS
        move_to_saldo_cero = request.POST.get('move_to_saldo_cero')#ESTE ES EL FORM DE SACAR LOS CLIENTES EN 0

        if move_to_saldo_cero:
            # Move all clients with saldo cero to a separate view
            return redirect('prestamosapp:clientes_con_saldo_cero')

        if cliente_id:
            cliente = get_object_or_404(Cliente, id=cliente_id)

            if payment_amount:
                # Handle payment processing
                payment_date = timezone.now()
                payment = Payment(cliente=cliente, payment_amount=payment_amount, payment_date=payment_date)
                payment.save()
                cliente.update_saldo()

            if move_to_saldo_cero:
                # Move client to saldo cero list
                cliente.saldo = 0
                cliente.save()
                return redirect('prestamosapp:cliente_list')  # Redirect to refresh the list

    # Query all clients
    clientes = Cliente.objects.all().order_by('order')
    clientes_con_saldo_cero = clientes.filter(saldo=0)
    clientes_con_saldo = clientes.exclude(saldo=0)
    total_pending = clientes_con_saldo.aggregate(total_saldo=Sum('saldo'))['total_saldo'] or 0
    
    context = {
        'clientes': clientes_con_saldo,  # Only include clients with saldo > 0
        'form': PaymentForm(),
        'total_pending': total_pending,
    }
    
    return render(request, 'cliente_list.html', context)
    

def clientes_con_saldo_cero(request):
    clientes_saldo_cero = Cliente.objects.filter(saldo=0).order_by('order')
    context = {
        'clientes': clientes_saldo_cero,
    }
    return render(request, 'clientes_con_saldo_cero.html', context)




def add_payment(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            payment_amount = form.cleaned_data['payment_amount']
            
            # Set payment_date to current datetime
            payment_date = timezone.now()
            
            payment = Payment(cliente=cliente, payment_amount=payment_amount, payment_date=payment_date)
            payment.save()
            
            # Update cliente's saldo
            cliente.update_saldo()
            
            return redirect('prestamosapp:cliente_list')
    else:
        form = PaymentForm()
    
    context = {
        'form': form,
        'cliente': cliente,
        'payments': cliente.get_payments(),
    }
    return render(request, 'cliente_list.html', context)



import pytz #ESTO LO TUBE QUE IMPORTAR PARA PODER PONER LA HORA DE MEXICO PORQUE NO ME LA ESTABA SACANDO CORRECTA Y TAMBIEN TUBE QUE CAMBIAR LA TIME_ZONE EN settings.py

#ESTO ES PARA VER LO QUE SE COBRO EN EL DIA 
def cobro_del_dia(request):
    mexico_tz = pytz.timezone('America/Mexico_City')
    now = timezone.now().astimezone(mexico_tz)
    today = now.date()
    
    start_of_day = mexico_tz.localize(timezone.datetime.combine(today, timezone.datetime.min.time()))
    end_of_day = mexico_tz.localize(timezone.datetime.combine(today, timezone.datetime.max.time()))

    payments_today = Payment.objects.filter(payment_date__range=(start_of_day, end_of_day))
    total_payments_today = payments_today.aggregate(total=Sum('payment_amount'))['total'] or 0

    context = {
        'total_payments_today': total_payments_today,
        'date': now.strftime("%d %B %Y"),
        'start_of_day': start_of_day.strftime("%d %B %Y %I:%M %p"),
        'end_of_day': end_of_day.strftime("%d %B %Y %I:%M %p")
    }

    return render(request, 'daily_payments_summary.html', context)

def historial_cobro(request):
    # Define the timezone
    mexico_tz = pytz.timezone('America/Mexico_City')
    now = timezone.now().astimezone(mexico_tz).date()
    
    # Get the earliest payment date from the Payment model
    earliest_payment = Payment.objects.order_by('payment_date').first()
    
    if not earliest_payment:
        # If there are no payments, return a message or handle this case as needed
        return render(request, 'daily_payments_summary.html', {'error': 'No payments found.'})
    
    start_date = earliest_payment.payment_date.date()
    
    # Generate a list of dates from start_date to today
    days_range = [start_date + timedelta(days=x) for x in range((now - start_date).days + 1)]

    daily_payments = []

    for day in days_range:
        start_of_day = mexico_tz.localize(timezone.datetime.combine(day, timezone.datetime.min.time()))
        end_of_day = mexico_tz.localize(timezone.datetime.combine(day, timezone.datetime.max.time()))

        payments_day = Payment.objects.filter(payment_date__range=(start_of_day, end_of_day))
        total_payments_day = payments_day.aggregate(total=Sum('payment_amount'))['total'] or 0

        daily_payments.append({
            'date': start_of_day.strftime("%d %B %Y"),
            'total_payments': total_payments_day
        })

    context = {
        'daily_payments': daily_payments,
    }
    return render(request, 'historial_de_cobros_diarios.html', context)



#METODO PARA BORRAR PAGO Y QUE SE REGRESE AL SALDO DEL CLIENTE 
def delete_payment(request, cliente_id, payment_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    payment = get_object_or_404(Payment, id=payment_id)

    # Save the payment amount to add back to the saldo
    deleted_payment_amount = payment.payment_amount
    
    # Delete the payment
    payment.delete()

    # Update cliente's saldo by adding back the deleted payment amount
    cliente.saldo += deleted_payment_amount
    cliente.save()

    return redirect('prestamosapp:cliente_list')



def edit_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == 'POST':
        form = ClienteForm(request.POST, request.FILES, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('prestamosapp:cliente_list')  # Redirect to client list or detail view
    else:
        form = ClienteForm(instance=cliente)
    
    context = {
        'form': form,
        'cliente': cliente,
    }
    return render(request, 'edit_cliente.html', context)


#ESTO ES PARA VER LO QUE SE COBRO EN EL DIA 



#ESTO ES PARA VER LOS PAGOS QUE HA HECHO CADA CLIENTE Y LA FECHA, PARA ESTO DEBI CREAR EL MODELO payment
def historial_de_pagos(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    payments = Payment.objects.filter(cliente=cliente).order_by('-payment_date')
    
    if request.method == 'POST':
        payment_id = request.POST.get('payment_id')
        if payment_id:
            payment = get_object_or_404(Payment, id=payment_id)
            # Get payment amount to add back to cliente's saldo
            payment_amount = payment.payment_amount
            # Delete the payment
            payment.delete()
            # Update cliente's saldo after deleting payment
            cliente.update_saldo()
            # Redirect to prevent re-submitting the form on refresh
            return redirect('prestamosapp:client_detail', cliente_id=cliente_id)
    
    context = {
        'cliente': cliente,
        'payments': payments,
    }
    return render(request, 'historial_de_pagos.html', context)

#SI EL USUARIO BORRA UN CLIENTE Y EL CLIENTE TIENE SALDO EL SALDO SE VA IR A LA BASE, PARA ESTO TUBE QUE AGREGAR UN METODO EN EL MODELO TAMBIEN
def borrar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    
    if request.method == 'POST':
        # Delete the cliente and redirect to cliente list or another appropriate page
        cliente.delete()
        return redirect('prestamosapp:cliente_list')  # Redirect to your client list URL name
    
    context = {
        'cliente': cliente,
    }
    return render(request, 'delete_cliente.html', context)


from prestamosapp.forms import AgregarGastoForm,AgregarBaseForm
from prestamosapp.models import AgregarGasto,AgregarBase

def agregar_gasto(request):

prestamosapp/templates/lista_gastos_de_la_semana.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%load static%}
    {%comment%}  META TAGS {%endcomment%}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="programador" content="christian stephen">
        <meta name="description" content="Desarrollador web Christian Stephen dedicado a crear sitios y aplicaciones que reflejen los valores y principios de tu negocio por medio del mundo digital. Comprometido con la excelencia técnica y la integridad ética en cada proyecto, utilizando mis habilidades para impactar positivamente en línea con mi trabajo.">
        <meta name="keywords" content="Desarrollo Web Puerto Vallarta Mexico, Desarrollador web de aplicaciones web, Sitios web acorde a las necesidades de tu negocio, Desarrollador web, Diseño web, Programación, programador web, Experto en desarrollo y hosting web, desarrollo digital">
        <meta name="robots" content="index, follow">
        <meta http-equiv="content-language" content="en, es">
        <meta name="title" content="Desarrollo Web 100% Personalizado | Métodos y Diseño Personalizado Dependiendo de las Necesidades de Tu negocio">
        <link rel="icon" href="{% static 'images/logo_turqueza.ico' %}" alt="logo pagina">

        <meta property="og:title" content="Puerto Vallarta Web Developer">
        <meta property="og:image" content="/static/images/logo_turqueza.png" type="image/png">
        <meta property="og:description" content="Desarrollador web Christian Stephen dedicado a crear sitios y aplicaciones que reflejen los valores y principios de tu negocio por medio del mundo digital. Comprometido con la excelencia técnica y la integridad ética en cada proyecto, utilizando mis habilidades para impactar positivamente en línea con mi trabajo.">
    {%comment%} FIN  META TAGS {%endcomment%}

  {%load static%}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gastos del Día</title>
    <link rel="stylesheet" href="{%static 'css/lista_gastos.css'%}">
</head>
<body>
    <div class="container">
        <h1>Gastos de la semana</h1>
        <table>
            <thead>
                <tr>
                    <th>Descripción</th>
                    <th>Monto</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                {% for gasto in gastos %}
                    <tr>
                        <td>{{ gasto.descripcion_gasto }}</td>
                        <td>${{ gasto.monto_gasto }}</td>
                        <td>{{ gasto.created_at.date }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="no-gastos">No hay gastos para hoy.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="total">Total: ${{ total|default:"0" }}
            <details>
                <summary>  Opciones </summary>
                {%if user.username == 'paquete2' %}
                        <a href="{% url 'paquete2:lista_gastos_del_dia' %}" class="button">Gastos de Hoy</a>
                        <a href="{% url 'paquete2:gastos_del_mes' %}" class="button">Gastos del Mes</a>        
                        <a href="{% url 'paquete2:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                        <a href="{% url 'paquete2:agregar_gasto' %}" class="button">Agregar Gasto</a>
                        <a href="{% url 'paquete2:cliente_list' %}" class="button">Lista de Clientes</a>

                {%elif user.username == 'paquete3' %}
                        <a href="{% url 'paquete3:lista_gastos_del_dia' %}" class="button">Gastos de Hoy</a>
                        <a href="{% url 'paquete3:gastos_del_mes' %}" class="button">Gastos del Mes</a>        
                        <a href="{% url 'paquete3:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                        <a href="{% url 'paquete3:agregar_gasto' %}" class="button">Agregar Gasto</a>
                        <a href="{% url 'paquete3:cliente_list' %}" class="button">Lista de Clientes</a>

                {%elif user.username == 'paquete4' %}
                        <a href="{% url 'paquete4:lista_gastos_del_dia' %}" class="button">Gastos de Hoy</a>
                        <a href="{% url 'paquete4:gastos_del_mes' %}" class="button">Gastos del Mes</a>        
                        <a href="{% url 'paquete4:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                        <a href="{% url 'paquete4:agregar_gasto' %}" class="button">Agregar Gasto</a>
                        <a href="{% url 'paquete4:cliente_list' %}" class="button">Lista de Clientes</a>
                
                {%elif user.username == 'paquete5' %}
                        <a href="{% url 'paquete5:lista_gastos_del_dia' %}" class="button">Gastos de Hoy</a>
                        <a href="{% url 'paquete5:gastos_del_mes' %}" class="button">Gastos del Mes</a>        
                        <a href="{% url 'paquete5:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                        <a href="{% url 'paquete5:agregar_gasto' %}" class="button">Agregar Gasto</a>
                        <a href="{% url 'paquete5:cliente_list' %}" class="button">Lista de Clientes</a>
                
                {%else%}
                        <a href="{% url 'prestamosapp:lista_gastos_del_dia' %}" class="button">Gastos de Hoy</a>
                        <a href="{% url 'prestamosapp:gastos_del_mes' %}" class="button">Gastos del Mes</a>        
                        <a href="{% url 'prestamosapp:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                        <a href="{% url 'prestamosapp:agregar_gasto' %}" class="button">Agregar Gasto</a>
                        <a href="{% url 'prestamosapp:cliente_list' %}" class="button">Lista de Clientes</a>
                {%endif%}
                </details>
        </div>
     
    </div>
</body>
</html>

prestamosapp/templates/lista_gastos_del_dia.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%load static%}
    <meta charset="UTF-8">
    {%comment%}  META TAGS {%endcomment%}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="programador" content="christian stephen">
        <meta name="description" content="Desarrollador web Christian Stephen dedicado a crear sitios y aplicaciones que reflejen los valores y principios de tu negocio por medio del mundo digital. Comprometido con la excelencia técnica y la integridad ética en cada proyecto, utilizando mis habilidades para impactar positivamente en línea con mi trabajo.">
        <meta name="keywords" content="Desarrollo Web Puerto Vallarta Mexico, Desarrollador web de aplicaciones web, Sitios web acorde a las necesidades de tu negocio, Desarrollador web, Diseño web, Programación, programador web, Experto en desarrollo y hosting web, desarrollo digital">
        <meta name="robots" content="index, follow">
        <meta http-equiv="content-language" content="en, es">
        <meta name="title" content="Desarrollo Web 100% Personalizado | Métodos y Diseño Personalizado Dependiendo de las Necesidades de Tu negocio">
        <link rel="icon" href="{% static 'images/logo_turqueza.ico' %}" alt="logo pagina">

        <meta property="og:title" content="Puerto Vallarta Web Developer">
        <meta property="og:image" content="/static/images/logo_turqueza.png" type="image/png">
        <meta property="og:description" content="Desarrollador web Christian Stephen dedicado a crear sitios y aplicaciones que reflejen los valores y principios de tu negocio por medio del mundo digital. Comprometido con la excelencia técnica y la integridad ética en cada proyecto, utilizando mis habilidades para impactar positivamente en línea con mi trabajo.">
    {%comment%} FIN  META TAGS {%endcomment%}

    <title>Gastos del Día</title>
    <link rel="stylesheet" href="{%static '/css/lista_gastos.css'%}">
</head>
<body>
    <div class="container">
        <h1>Gastos del Día</h1>
        <table>
            <thead>
                <tr>
                    <th>Descripción</th>
                    <th>Monto</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                {% for gasto in gastos %}
                    <tr>
                        <td>{{ gasto.descripcion_gasto }}</td>
                        <td>${{ gasto.monto_gasto }}</td>
                        <td>{{ gasto.created_at.date }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="no-gastos">No hay gastos para hoy.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="total">Total: ${{ total|default:"0" }}
            <details>
                <summary> Options</summary>
            {%if user.username == 'paquete2' %}
                <a href="{% url 'paquete2:gastos_semanales' %}" class="button">Gastos de la Semana</a>
                <a href="{% url 'paquete2:gastos_del_mes' %}" class="button">Gastos del Mes</a>
                <a href="{% url 'paquete2:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                <a href="{% url 'paquete2:agregar_gasto' %}" class="button">Agregar Gasto</a>
                <a href="{% url 'paquete2:cliente_list' %}" class="button">Lista de Clientes</a>

            {%elif user.username == 'paquete3' %}
                <a href="{% url 'paquete3:gastos_semanales' %}" class="button">Gastos de la Semana</a>
                <a href="{% url 'paquete3:gastos_del_mes' %}" class="button">Gastos del Mes</a>
                <a href="{% url 'paquete3:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                <a href="{% url 'paquete3:agregar_gasto' %}" class="button">Agregar Gasto</a>
                <a href="{% url 'paquete3:cliente_list' %}" class="button">Lista de Clientes</a>

            {%elif user.username == 'paquete4' %}
                <a href="{% url 'paquete4:gastos_semanales' %}" class="button">Gastos de la Semana</a>
                <a href="{% url 'paquete4:gastos_del_mes' %}" class="button">Gastos del Mes</a>
                <a href="{% url 'paquete4:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                <a href="{% url 'paquete4:agregar_gasto' %}" class="button">Agregar Gasto</a>
                <a href="{% url 'paquete4:cliente_list' %}" class="button">Lista de Clientes</a>

            {%elif user.username == 'paquete5' %}
                <a href="{% url 'paquete5:gastos_semanales' %}" class="button">Gastos de la Semana</a>
                <a href="{% url 'paquete5:gastos_del_mes' %}" class="button">Gastos del Mes</a>
                <a href="{% url 'paquete5:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                <a href="{% url 'paquete5:agregar_gasto' %}" class="button">Agregar Gasto</a>
                <a href="{% url 'paquete5:cliente_list' %}" class="button">Lista de Clientes</a>

            {%else%}   
                <a href="{% url 'prestamosapp:gastos_semanales' %}" class="button">Gastos de la Semana</a>
                <a href="{% url 'prestamosapp:gastos_del_mes' %}" class="button">Gastos del Mes</a>
                <a href="{% url 'prestamosapp:todos_los_gastos' %}" class="button">Todos los Gastos</a>
                <a href="{% url 'prestamosapp:agregar_gasto' %}" class="button">Agregar Gasto</a>
                <a href="{% url 'prestamosapp:cliente_list' %}" class="button">Lista de Clientes</a>
            {%endif%}
            </details>
    </div>
    </div>
</body>
</html>